shell = "zsh"

[plugins]

[plugins.zsh-defer]
github = "romkatv/zsh-defer"

[plugins.zsh-autocomplete]
github = "marlonrichert/zsh-autocomplete"
# apply = ["defer"]

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
apply = ["defer"]

[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"
# apply = ["defer"]

[plugins.zsh-completions]
github = "zsh-users/zsh-completions"
apply = ["defer"]

[plugins.zsh-history-substring-search]
github = "zsh-users/zsh-history-substring-search"
apply = ["defer"]

[plugins.zsh-navigation-tools]
github = "psprint/zsh-navigation-tools"

[plugins.zsh-abbr]
github = "olets/zsh-abbr"
apply = ["defer"]

[plugins.local-zsh-completions]
local = "~/.config/zsh/site-functions/"
apply = ["fpath"]

[plugins.homebrew]
inline = 'eval "$(/opt/homebrew/bin/brew shellenv)"'

[plugins.starship]
inline = 'eval "$(starship init zsh)"'

[plugins.compinit]
inline = "autoload -Uz compinit && compinit"

[plugins.cdr]
inline = "autoload -Uz chpwd_recent_dirs cdr add-zsh-hook && add-zsh-hook chpwd chpwd_recent_dirs"

[plugins.local-plugins]
local = "~/.config/zsh/plugins/"
apply = ["source"]

[templates]
defer = "{% for file in files %}zsh-defer source \"{{ file }}\"\n{% endfor %}"
