[tools]
gh = "latest"
node = "22"
peco = "latest"
pnpm = "10"
ghq = "latest"
chezmoi = "latest"
age = "latest"
go = "1.24.1"
podman = "latest"
bitwarden = "latest"
starship = "latest"
cargo-binstall = "latest"
"cargo:sheldon" = "latest"
eza = "latest"
cfssl = "latest"
cmake = "latest"
colima = "latest"
lima = "latest"
ffmpeg = "latest"
fzf = "latest"
grpcurl = "latest"
helm = "latest"
helmfile = "latest"
jq = "latest"
k9s = "latest"
kubectl = "latest"
lazygit = "latest"
make = "latest"
neovim = "latest"
xh = "latest"
yq = "latest"
