[general]
live_config_reload = true
import = ["./tokyo_night.toml"]

[terminal]
shell = { program = "/bin/zsh", args = [
  "-l",
  "-c",
  "tmux a -t default || tmux new -s default",
] }

[window]
dimensions = { columns = 192, lines = 64 }
opacity = 0.9
padding = { x = 12, y = 16 }
decorations = "transparent"

[font]
size = 13.0
normal.family = "0xProto Nerd Font"
offset.y = 1
