[tools]
"npm:@anthropic-ai/claude-code" = "latest"
"npm:ccusage" = "latest"
"npm:@cyanheads/git-mcp-server" = "latest"
"npm:markdownlint-cli" = "latest"
"npm:@google/gemini-cli" = "latest"
uv = "latest"
"pipx:mcp-server-git" = "latest"
"npm:@mjpitz/mcp-rfc" = "latest"
"pipx:mcp-server-fetch" = "latest"
