shell = "zsh"

[plugins]

[plugins.zsh-defer]
github = "romkatv/zsh-defer"

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
apply = ["defer"]

[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"

[plugins.zsh-autocomplete]
github = "marlonrichert/zsh-autocomplete"

[plugins.zsh-completions]
github = "zsh-users/zsh-completions"
apply = ["defer"]

[plugins.zsh-history-substring-search]
github = "zsh-users/zsh-history-substring-search"
apply = ["defer"]

[plugins.zsh-navigation-tools]
github = "psprint/zsh-navigation-tools"
apply = ["defer"]

[plugins.local-zsh-completions]
local = "~/.config/zsh/site-functions/"
apply = ["defer", "fpath"]

[plugins.homebrew]
inline = 'eval "$(/opt/homebrew/bin/brew shellenv)"'

[plugins.mise]
inline = '''
eval "$(mise activate zsh)"
path=(
  ${HOME}/.local/share/mise/shims(N-/)
  $path
)
'''

[plugins.starship]
inline = 'eval "$(starship init zsh)"'

[plugins.compinit]
inline = """
autoload -Uz compinit
zsh-defer -a -t0.01 compinit -d "$XDG_STATE_HOME/zsh/zcompdump"
"""

[plugins.cdr]
inline = "autoload -Uz chpwd_recent_dirs cdr add-zsh-hook && add-zsh-hook chpwd chpwd_recent_dirs"

[plugins.local-plugins]
local = "~/.config/zsh/plugins/"
apply = ["defer"]

[templates]
defer = "{% for file in files %}zsh-defer source \"{{ file }}\"\n{% endfor %}"
