name: Dotfiles CI
on:
  push:
    paths-ignore:
      - ".claude/**"
      - ".vscode/**"
      - ".editorconfig"
      - "CLAUDE.md"
      - "README.md"
      - "LICENSE"

jobs:
  apply_test:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-apply_test-${{ matrix.os }}
      cancel-in-progress: true
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Load age secret key
        run: |
          mkdir -p ~/.config/chezmoi
          echo "${{ env.CHEZMOI_ENCRYPT_KEY }}" > ~/.config/chezmoi/key.txt
          chmod 600 ~/.config/chezmoi/key.txt
        env:
          CHEZMOI_ENCRYPT_KEY: ${{ secrets.CHEZMOI_ENCRYPT_KEY }}

      - name: Run chezmoi apply
        run: sh -c "$(curl -fsLS get.chezmoi.io)" -- init --apply -S .
