name: Dotfiles CI
on:
  push:

jobs:
  apply_test:
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-apply_test
      cancel-in-progress: true
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Load age secret key
        run: |
          mkdir -p ~/.config/chezmoi
          echo "${{ env.CHEZMOI_ENCRYPT_KEY }}" > ~/.config/chezmoi/key.txt
        env:
          CHEZMOI_ENCRYPT_KEY: ${{ secrets.CHEZMOI_ENCRYPT_KEY }}

      - name: Install packages from Brewfile (excluding MAS)
        run: |
          # chezmoiでBrowfileを生成
          sh -c "$(curl -fsLS get.chezmoi.io)" -- init ${{ github.repository_owner }}
          
          # MASを除外してBrew Bundleを実行
          grep -v "^mas " ~/.Brewfile | brew bundle --file=-
          
      - name: Run chezmoi apply (without brew bundle)
        run: |
          # Brewfileを一時的にリネームしてBrew Bundleの実行を回避
          mv ~/.Brewfile ~/.Brewfile.bak || true
          chezmoi apply -v
          # Brewfileを元に戻す
          mv ~/.Brewfile.bak ~/.Brewfile || true
