name: Semantic PR title
on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - edited
      - reopened
      - synchronize

permissions: {}

jobs:
  semantic-pr-title:
    name: Check PR title
    permissions:
      pull-requests: read
    uses: cffnpwr/actions/.github/workflows/semantic-pr-title.yaml@03825f885ab5edf937a4bb6a8b0a7d9759de21d3
